version: "3.8"

services:
  gstreamer:
    build: .
    volumes:
    - /dev/bus/usb:/dev/bus/usb
    privileged: true
    restart: unless-stopped

  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
    - 8554:8554
    - 8889:8889
    - 8189:8189/udp
    environment:
    - MTX_WEBRTCADDITIONALHOSTS=avatour.duckdns.org
    restart: unless-stopped
