services:
  gstreamer:
    volumes:
    - /dev/bus/usb:/dev/bus/usb
    privileged: true
    restart: unless-stopped
    build: .
  mediamtx:
    image: bluenviron/mediamtx:latest
    ports:
    - 8554:8554
    restart: unless-stopped
